# Generated by Django 3.0.8 on 2020-10-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_org',
            field=models.BooleanField(default=False),
        ),
    ]
