# Generated by Django 3.0.8 on 2020-10-26 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201025_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('bio', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('contact_name', models.CharField(max_length=300)),
                ('org_bio', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='is organisation'),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
