# Generated by Django 3.0.8 on 2020-10-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201026_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='org_bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
