# Generated by Django 3.0.8 on 2020-10-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201026_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
