# Generated by Django 3.0.8 on 2020-10-28 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201028_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='skills',
            field=models.ManyToManyField(related_name='mentors', to=settings.AUTH_USER_MODEL),
        ),
    ]
