# Generated by Django 3.0.8 on 2020-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201105_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=-31.95351, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='location',
            field=models.CharField(default='Perth, WA, Australia', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=115.85705, max_digits=15),
        ),
    ]
