# Generated by Django 3.0.8 on 2020-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201105_0732'),
        ('users', '0010_auto_20201105_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='skills',
            field=models.ManyToManyField(related_name='mentors', to='events.Category'),
        ),
    ]
