# Generated by Django 3.0.8 on 2020-11-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentor_image',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/03/03/08/55/portrait-657116_960_720.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='org_image',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/03/03/08/55/portrait-657116_960_720.jpg', null=True),
        ),
    ]
