# Generated by Django 3.0.8 on 2020-10-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201027_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', related_query_name='event', to='events.Category'),
        ),
    ]
