# Generated by Django 3.0.8 on 2020-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_category_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
