# Generated by Django 3.0.8 on 2020-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201105_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
