# Generated by Django 3.0.8 on 2020-11-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201107_1108'),
        ('events', '0017_auto_20201107_1239'),
    ]

    operations = [
    ]
