# Generated by Django 3.0.8 on 2020-11-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_merge_20201109_0613'),
        ('events', '0019_merge_20201108_1342'),
    ]

    operations = [
    ]
